name: flutter_tex

description: A Flutter Package to render Mathematics / Maths, Physics and Chemistry, Statistics Equations and expressions based on LaTeX, TeX, and MathML with HTML and JavaScript support.

version: 4.0.8

homepage: https://github.com/shah-xad/flutter_tex

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  webview_flutter_plus: ^0.4.6
  markdown: ^7.2.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - packages/flutter_tex/js/flutter_tex.js
    - packages/flutter_tex/js/flutter_tex.css
    # MathJax
    - packages/flutter_tex/js/mathjax/extensions/MathEvents.js
    - packages/flutter_tex/js/mathjax/extensions/MathZoom.js
    - packages/flutter_tex/js/mathjax/extensions/AssistiveMML.js
    - packages/flutter_tex/js/mathjax/extensions/CHTML-preview.js
    - packages/flutter_tex/js/mathjax/extensions/Safe.js
    - packages/flutter_tex/js/mathjax/extensions/tex2jax.js
    - packages/flutter_tex/js/mathjax/extensions/asciimath2jax.js
    - packages/flutter_tex/js/mathjax/extensions/jsMath2jax.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/extpfeil.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/AMScd.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/mathchoice.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/color.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/mhchem.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/verb.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/mediawiki-texvc.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/AMSmath.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/bbox.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/HTML.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/action.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/newcommand.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/cancel.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/noErrors.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/autobold.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/noUndefined.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/unicode.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/enclose.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/autoload-all.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/begingroup.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/AMSsymbols.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/mhchem3/mhchem.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/text-macros.js
    - packages/flutter_tex/js/mathjax/extensions/TeX/boldsymbol.js
    - packages/flutter_tex/js/mathjax/extensions/MathMenu.js
    - packages/flutter_tex/js/mathjax/extensions/HelpDialog.js
    - packages/flutter_tex/js/mathjax/extensions/MatchWebFonts.js
    - packages/flutter_tex/js/mathjax/extensions/toMathML.js
    - packages/flutter_tex/js/mathjax/extensions/fast-preview.js
    - packages/flutter_tex/js/mathjax/extensions/mml2jax.js
    - packages/flutter_tex/js/mathjax/extensions/MathML/content-mathml.js
    - packages/flutter_tex/js/mathjax/extensions/MathML/mml3.js
    - packages/flutter_tex/js/mathjax/extensions/FontWarnings.js
    - packages/flutter_tex/js/mathjax/jax/input/TeX/config.js
    - packages/flutter_tex/js/mathjax/jax/input/TeX/jax.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/f.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/d.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/l.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/i.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/g.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/b.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/z.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/h.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/a.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/j.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/s.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/q.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/r.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/u.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/y.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/k.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/fr.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/n.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/e.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/m.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/v.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/p.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/opf.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/scr.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/c.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/x.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/w.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/t.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/entities/o.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/config.js
    - packages/flutter_tex/js/mathjax/jax/input/MathML/jax.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/jax.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/MiscTechnical.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/MiscMathSymbolsB.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/CombDiacritMarks.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/GeometricShapes.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/SupplementalArrowsA.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/Dingbats.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/SpacingModLetters.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/MathOperators.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/MiscSymbolsAndArrows.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/CombDiactForSymbols.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/GeneralPunctuation.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/GreekAndCoptic.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/Latin1Supplement.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/MiscMathSymbolsA.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/Arrows.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/BasicLatin.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/SuppMathOperators.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/SupplementalArrowsB.js
    - packages/flutter_tex/js/mathjax/jax/element/mml/optable/LetterlikeSymbols.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/menclose.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/multiline.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/annotation-xml.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/ms.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/maction.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/mglyph.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/mtable.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/autoload/mmultiscripts.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/config.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/jax.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/DoubleStruck/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Arrows/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Fraktur/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Symbols/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Marks/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Alphabets/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Shapes/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Misc/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/NonUnicode/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Normal/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Variants/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Size4/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Size2/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Main/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Size3/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Monospace/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/fontdata-extra.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Size5/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Size6/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Latin/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/SansSerif/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/fontdata.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Operators/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Size1/Regular/Main.js
    - packages/flutter_tex/js/mathjax/jax/output/SVG/fonts/Gyre-Pagella/Script/Regular/Main.js
    - packages/flutter_tex/js/mathjax/LICENSE
    - packages/flutter_tex/js/mathjax/MathJax.js
    - packages/flutter_tex/js/mathjax/index.html
    # Katex
    - packages/flutter_tex/js/katex/index.html
    - packages/flutter_tex/js/katex/contrib/auto-render.min.js
    - packages/flutter_tex/js/katex/contrib/mathtex-script-type.min.js
    - packages/flutter_tex/js/katex/contrib/mhchem.min.js
    - packages/flutter_tex/js/katex/fonts/KaTeX_AMS-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_AMS-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_AMS-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Caligraphic-Bold.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Caligraphic-Bold.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Caligraphic-Bold.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Caligraphic-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Caligraphic-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Caligraphic-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Fraktur-Bold.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Fraktur-Bold.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Fraktur-Bold.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Fraktur-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Fraktur-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Fraktur-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-BoldItalic.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-BoldItalic.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-BoldItalic.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Bold.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Bold.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Bold.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Italic.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Italic.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Italic.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Main-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Math-BoldItalic.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Math-BoldItalic.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Math-BoldItalic.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Math-Italic.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Math-Italic.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Math-Italic.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Bold.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Bold.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Bold.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Italic.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Italic.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Italic.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_SansSerif-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Script-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Script-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Script-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size1-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size1-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size1-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size2-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size2-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size2-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size3-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size3-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size3-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size4-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size4-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Size4-Regular.woff2
    - packages/flutter_tex/js/katex/fonts/KaTeX_Typewriter-Regular.ttf
    - packages/flutter_tex/js/katex/fonts/KaTeX_Typewriter-Regular.woff
    - packages/flutter_tex/js/katex/fonts/KaTeX_Typewriter-Regular.woff2
    - packages/flutter_tex/js/katex/katex.min.css
    - packages/flutter_tex/js/katex/katex.min.js